version: '3.1'
services:
  node1:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  node2:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  node3:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  visualizer:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  nginx:
    image: klotzandrew/dockernodenginxsetup_nginx
    ports:
      - "80:80"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
