version: '3.1'
services:
  node1:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  node2:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  node3:
    image: klotzandrew/dockernodenginxsetup_node1
    ports:
      - '3000'

  nginx:
    image: klotzandrew/dockernodenginxsetup_nginx
    ports:
      - "80:80"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
