version: '3.1'
services:
  node:
    image: klotzandrew/dockernodenginxsetup_node
    ports:
      - '3000:3000'

  visualizer:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  nginx:
    image: klotzandrew/dockernodenginxsetup_nginx
    ports:
      - "80:80"
    depends_on:
      - node
